# Generated by Django 5.0.6 on 2024-10-28 18:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('order_detail_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=300)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_quantity', models.IntegerField()),
                ('product_total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Order Detail',
                'verbose_name_plural': 'Order Details',
                'db_table': 'order_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('order_status', models.CharField(max_length=50)),
                ('order_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_payment_id', models.CharField(max_length=100)),
                ('order_invoice_id', models.CharField(max_length=100)),
                ('order_total_quantity', models.IntegerField()),
                ('order_shipped_address', models.CharField(max_length=500)),
                ('order_shipped_city', models.CharField(max_length=100)),
                ('order_shipped_state', models.CharField(max_length=300)),
                ('order_shipped_zip', models.CharField(max_length=10)),
                ('order_shipped_country', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parent_Category',
            fields=[
                ('parent_category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parent_category_name', models.CharField(max_length=100, unique=True)),
                ('parent_category_description', models.TextField(blank=True)),
                ('parent_category_active', models.BooleanField(default=True)),
                ('parent_category_added_date', models.DateTimeField(auto_now_add=True)),
                ('parent_category_modified_date', models.DateTimeField(auto_now=True)),
                ('parent_category_removed_date', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name_plural': 'parent_categories',
            },
        ),
        migrations.CreateModel(
            name='Sub_Sub_Category',
            fields=[
                ('sub_sub_category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sub_sub_category_name', models.CharField(max_length=100, unique=True)),
                ('sub_sub_category_description', models.TextField(blank=True)),
                ('sub_sub_category_active', models.BooleanField(default=True)),
                ('sub_sub_category_added_date', models.DateTimeField(auto_now_add=True)),
                ('sub_sub_category_modified_date', models.DateTimeField(auto_now=True)),
                ('sub_sub_category_removed_date', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name_plural': 'sub_sub_categories',
            },
        ),
        migrations.CreateModel(
            name='Sub_Category',
            fields=[
                ('sub_category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sub_category_name', models.CharField(max_length=100)),
                ('sub_category_description', models.TextField(blank=True)),
                ('sub_category_active', models.BooleanField(default=True)),
                ('sub_category_added_date', models.DateTimeField(auto_now_add=True)),
                ('sub_category_modified_date', models.DateTimeField(auto_now=True)),
                ('sub_category_removed_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.parent_category')),
            ],
            options={
                'verbose_name_plural': 'sub_categories',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.TextField(blank=True)),
                ('product_active', models.BooleanField(default=True)),
                ('product_added_date', models.DateTimeField(auto_now_add=True)),
                ('product_modified_date', models.DateTimeField(auto_now=True)),
                ('product_removed_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.sub_category')),
            ],
            options={
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='Sub_Sub_Category_Sub_Category_Connector',
            fields=[
                ('sub_sub_category_sub_category_connector_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sub_sub_category_sub_category_connector_added_date', models.DateTimeField(auto_now_add=True)),
                ('sub_sub_category_sub_category_connector_modified_date', models.DateTimeField(auto_now=True)),
                ('sub_sub_category_sub_category_connector_removed_date', models.DateTimeField(blank=True, null=True)),
                ('sub_sub_category_sub_category_connector_active', models.BooleanField(default=True)),
                ('sub_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.sub_category')),
                ('sub_sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.sub_sub_category')),
            ],
            options={
                'verbose_name_plural': 'sub_sub_category_sub_category_connectors',
            },
        ),
    ]
